### ISSUE TITLE
Kill jQuery

### ISSUE THREAD

**Issue by MadaraUchiha** [IonicaBizau/github-profile-languages#1]
I intend to try at a pull request. What browser support are you expecting from this?

**Comment by IonicaBizau** [comment]
Probably just the modern browsers... I don't like jQuery for such projects but since `drawPieChart` (which I really liked) requires it, I made this compromise. :smile: 

But sure, if you find a non-jQuery way, with friendly animations I'd really like to accept that. :+1:

**Comment by IonicaBizau** [comment]
Fixed via #2.
