### ISSUE TITLE
Including private repositories

### ISSUE THREAD

**Issue by haideralipunjabi** [IonicaBizau/github-profile-languages#19]
I think it should be added as an enhancement

**Comment by IonicaBizau** [comment]
This should work already for the `api.html` endpoint:

 1. [Create a token](https://github.com/settings/tokens/new) (note: it should have the `repo` scope)
 2. `http://ionicabizau.github.io/github-profile-languages/api?token=<your-token>&input=<owner>/<repo>`

I see the following limitations:

 - There's no way to provide the token in the UI
 - It seems like it doesn't fetch the private repositories even with a strong enough token. The API endpoint may be not returning these.

Contributions are welcome! :sparkle:

**Comment by haideralipunjabi** [comment]
That might work for each repository, is it possible do it for my whole profile. All repos (private + public)
