### ISSUE TITLE
automatically fit the pie in the allocated region

### ISSUE THREAD

**Issue by DamienAllonsius** [IonicaBizau/github-profile-languages#25]
Hi ! 
First of all : great job :clap: :clap: 
So I was trying to add my pie on my webpage (see https://damienallonsius.github.io/) at the very bottom of the page, to show my repos.
I use the following command in my index.html
```
<iframe  id="Gitframe" height="300px" width="700px" src="https://damienAllonsius.github.io/github-profile-languages/api.html?damienAllonsius" frameborder="0"></iframe>
```
Unfortunately, the pie does not fit in the box 300x700 and a scrollable window appears instead of the whole chart. Is it possible to reshape the pie automatically so that it fits in the prescribed box ?

Thanks a lot for your help
Cheers

PS: another question, where can I change the size of the legend ?

**Comment by IonicaBizau** [comment]
Contributions would really be appreciated in this sense. Thanks!
