### ISSUE TITLE
Pie Chart for Repository

### ISSUE THREAD

**Issue by y12uc231** [IonicaBizau/github-profile-languages#3]
Is it possible to add another facility for showing all the programming languages used in a single repository by providing repo address (for eg. IonicaBizau/github-profile-languages )?

**Comment by IonicaBizau** [comment]
That's a neat idea! :sparkles: 

For this we have to use the [language listing provided by GitHub API](https://developer.github.com/v3/repos/#list-languages).

``` sh
$ curl https://api.github.com/repos/IonicaBizau/github-profile-languages/languages
{
  "HTML": 3220,
  "CSS": 4499,
  "JavaScript": 27231
}
```

**Comment by IonicaBizau** [comment]
@y12uc231 Would you like to implement this?

**Comment by y12uc231** [comment]
I want to implement this but my exams are on...so it may take a month's time.

**Comment by IonicaBizau** [comment]
I'm on it.

**Comment by IonicaBizau** [comment]
Check #6. :smile:

**Comment by y12uc231** [comment]
It Still has some problem
![capture](https://cloud.githubusercontent.com/assets/5621640/7790780/18106858-02b0-11e5-9556-138efc7e6b4d.JPG)

**Comment by IonicaBizau** [comment]
@y12uc231 Because it's not merged yet. You can test it by cloning this repository on your machine and do `git checkout polyglot`, to checkout the feature branch. :sparkle:

**Comment by IonicaBizau** [comment]
:ship: 2.0.0
