### ISSUE TITLE
Not compatible with github md files

### ISSUE THREAD

**Issue by khaleb-dev** [IonicaBizau/github-profile-languages#31]
Hello, I tried to embed the chart on my readme.md file for my account but was unable to do so.

I suggest that the chart should have a way of embedding it into readme.md files on Github.

Heres a  similar project: https://github.com/anuraghazra/github-readme-stats

**Comment by rafaelfaustini** [comment]
It seems that if there were an URL that generates, only the pure image, Github Markdown would work.

**Comment by IonicaBizau** [comment]
Well, this project is not designed to be embeded in markdown files unless the renderer supports iframes. Like @rafaelfaustini, you can use a service that generates an image instead.
