### ISSUE TITLE
Links to non-existent URL when @ is used for username

### ISSUE THREAD

**Issue by Unihedro** [IonicaBizau/github-profile-languages#4]
![](http://i.gyazo.com/28aad4beff6bbd4f5132850d5506df47.png)

Clicking on the text selected by the freehand square leads me to:

![](http://gyazo.com/892e26d6165d9ca0efc83668c6591173.png)

**Comment by IonicaBizau** [comment]
That'a good point! :+1: 

[Here](https://github.com/IonicaBizau/github-profile-languages/blob/f45ed23617edddbdb8b6707a76f764e518e5c37d/js/main.js#L72) we have to do `user.replace(/^\@/, "")`. But you know better. :smile:
